apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    course: Dev-Ops
    Trainer: krishna
  annotations:
    com.roboshop.training.duration: "120hrs"
spec:
  containers:
  - name: nginx
    image: nginx
    containerPort: 80
