apiVersion: v1
kind: Pod
metadata:
  name: env
  labels:
    course: Dev-Ops
    Trainer: krishna
  annotations:
    com.roboshop.training.duration: "120hrs"
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: demo
      value: harekrishna
    - name: demo1
      value: harerama  