apiVersion: v1
kind: Pod
metadata:
  name: harekrishna-pod
  #namespace: roboshop
spec:
  containers:
  - name: harekrishna-pod
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "68Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"


